search_config.settings:
    type:config_object
        mapping:
            toggle_forms:
                type: integer
                label: 'Only show one form at a time'
            move_keyword_search:
                type: integer
                label: 'Move basic move_keyword_search'
            advanced_populate:
                type: integer
                label: 'Populate the advanced form with default values'
            advanced_expand:
                type: integer
                label: 'Control how the advanced form initially renders'
            remove_containing_wrapper:
                type: integer
                label: 'Remove all Containing ... keyword options'
            containing_any:
                type: string
                label: 'Containing any ...'
            containing_phrase:
                type: string
                label: 'Containing the phrase'
            containing_none:
                type: string
                label: 'Containing none ...'
            types:
                type: string
                label: 'Types'
            category:
                type: string
                label: 'Replace type options with custom type groups'
            language:
                type: string
                label: 'Language selector'
            limit:
                type: integer
                label: 'Pager Limit'
            admin_bypass:
                type: integer
                label: 'Admin bypass'
            remove_advanced:
                type: integer
                label: 'Remove advanced search unconditionally'
